/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 100136
 Source Host           : localhost:3306
 Source Schema         : aland

 Target Server Type    : MySQL
 Target Server Version : 100136
 File Encoding         : 65001

 Date: 25/02/2019 09:48:13
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for expert
-- ----------------------------
DROP TABLE IF EXISTS `expert`;
CREATE TABLE `expert`  (
  `expert_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `description` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `images` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `detail` longtext CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `publish` tinyint(1) UNSIGNED NULL DEFAULT 1,
  `share_url` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `seo_title` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `seo_description` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `seo_keyword` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `create_time` int(10) UNSIGNED NULL DEFAULT NULL,
  `update_time` int(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`expert_id`) USING BTREE,
  INDEX `idx_news_1`(`publish`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 37578 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of expert
-- ----------------------------
INSERT INTO `expert` VALUES (37568, 'Ms Hoa Toeic', '<ul>\r\n <li>Tốt nghiệp ĐH Ngoại Thương</li>\r\n <li>Ielts: 7.5</li>\r\n <li>Du học sinh: Anh</li>\r\n <li>Hạnh kiểm tốt</li>\r\n</ul>\r\n', '1.jpg', '<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n', 1, '/expert/ms-hoa-toeic-37568.html', '', '', '', 1551062597, 1551062864);
INSERT INTO `expert` VALUES (37569, 'Ms Hoa Toeic', '<ul>\r\n <li>Tốt nghiệp ĐH Ngoại Thương</li>\r\n <li>Ielts: 7.5</li>\r\n <li>Du học sinh: Anh</li>\r\n <li>Hạnh kiểm tốt</li>\r\n</ul>\r\n', '1.jpg', '<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n', 1, '/expert/ms-hoa-toeic-37569.html', '', '', '', 1551062597, 1551062597);
INSERT INTO `expert` VALUES (37570, 'Ms Hoa Toeic', '<ul>\r\n <li>Tốt nghiệp ĐH Ngoại Thương</li>\r\n <li>Ielts: 7.5</li>\r\n <li>Du học sinh: Anh</li>\r\n <li>Hạnh kiểm tốt</li>\r\n</ul>\r\n', '1.jpg', '<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n', 1, '/expert/ms-hoa-toeic-37570.html', '', '', '', 1551062597, 1551062597);
INSERT INTO `expert` VALUES (37571, 'Ms Hoa Toeic', '<ul>\r\n <li>Tốt nghiệp ĐH Ngoại Thương</li>\r\n <li>Ielts: 7.5</li>\r\n <li>Du học sinh: Anh</li>\r\n <li>Hạnh kiểm tốt</li>\r\n</ul>\r\n', '1.jpg', '<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n', 1, '/expert/ms-hoa-toeic-37571.html', '', '', '', 1551062597, 1551062597);
INSERT INTO `expert` VALUES (37572, 'Ms Hoa Toeic', '<ul>\r\n <li>Tốt nghiệp ĐH Ngoại Thương</li>\r\n <li>Ielts: 7.5</li>\r\n <li>Du học sinh: Anh</li>\r\n <li>Hạnh kiểm tốt</li>\r\n</ul>\r\n', '1.jpg', '<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n', 1, '/expert/ms-hoa-toeic-37572.html', '', '', '', 1551062597, 1551062597);
INSERT INTO `expert` VALUES (37573, 'Ms Hoa Toeic', '<ul>\r\n <li>Tốt nghiệp ĐH Ngoại Thương</li>\r\n <li>Ielts: 7.5</li>\r\n <li>Du học sinh: Anh</li>\r\n <li>Hạnh kiểm tốt</li>\r\n</ul>\r\n', '1.jpg', '<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n', 1, '/expert/ms-hoa-toeic-37573.html', '', '', '', 1551062597, 1551062597);
INSERT INTO `expert` VALUES (37574, 'Ms Hoa Toeic', '<ul>\r\n <li>Tốt nghiệp ĐH Ngoại Thương</li>\r\n <li>Ielts: 7.5</li>\r\n <li>Du học sinh: Anh</li>\r\n <li>Hạnh kiểm tốt</li>\r\n</ul>\r\n', '1.jpg', '<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n', 1, '/expert/ms-hoa-toeic-37574.html', '', '', '', 1551062597, 1551062597);
INSERT INTO `expert` VALUES (37575, 'Ms Hoa Toeic', '<ul>\r\n <li>Tốt nghiệp ĐH Ngoại Thương</li>\r\n <li>Ielts: 7.5</li>\r\n <li>Du học sinh: Anh</li>\r\n <li>Hạnh kiểm tốt</li>\r\n</ul>\r\n', '1.jpg', '<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n', 1, '/expert/ms-hoa-toeic-37575.html', '', '', '', 1551062597, 1551062597);
INSERT INTO `expert` VALUES (37576, 'Ms Hoa Toeic', '<ul>\r\n <li>Tốt nghiệp ĐH Ngoại Thương</li>\r\n <li>Ielts: 7.5</li>\r\n <li>Du học sinh: Anh</li>\r\n <li>Hạnh kiểm tốt</li>\r\n</ul>\r\n', '1.jpg', '<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n', 1, '/expert/ms-hoa-toeic-37576.html', '', '', '', 1551062597, 1551062597);
INSERT INTO `expert` VALUES (37577, 'Ms Hoa Toeic', '<ul>\r\n <li>Tốt nghiệp ĐH Ngoại Thương</li>\r\n <li>Ielts: 7.5</li>\r\n <li>Du học sinh: Anh</li>\r\n <li>Hạnh kiểm tốt</li>\r\n</ul>\r\n', '1.jpg', '<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n\r\n<p>Ms Hoa Giao tiếp xây dựng mô hình thực hành tiếng Anh Giao tiếp số 1 Việt Nam với phương pháp Phản xạ kết hợp với Truyền cảm hứng, giúp học viên khám phá vẻ đẹp của Tiếng Anh, từ đó theo đuổi, nuôi dưỡng tình yêu tiếng Anh ngày một lớn hơn. </p>\r\n', 1, '/expert/ms-hoa-toeic-37577.html', '', '', '', 1551062597, 1551062597);

SET FOREIGN_KEY_CHECKS = 1;
